# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
  - glean_taskgraph.transforms.script_to_run_task:transforms
  - taskgraph.transforms.job:transforms
  - taskgraph.transforms.task:transforms

job-defaults:
  worker-type: b-linux
  worker:
    docker-image: {in-tree: linux}
    max-run-time: 1800
  run:
    using: run-task
    cwd: '{checkout}'

jobs:
  clippy:
    description: 'Rust: Clippy'
    run:
      script: |
          . ./taskcluster/scripts/rust/rustup-setup.sh
          rustup component add clippy
          cargo clippy --version
          cargo clippy --all --all-targets --all-features -- -D warnings
  tests:
    description: 'Rust: Tests'
    run:
      script: |
          . ./taskcluster/scripts/rust/rustup-setup.sh
          cargo test --all --verbose
