[book]
title = "Glean - Cross-platform Telemetry library"
authors = ["Jan-Erik Rediger", "Glean Team"]
src = "."

[build]
build-dir = "book"
create-missing = false

[output.html]
additional-css = ["tabs.css"]
additional-js = ["tabs.js"]